//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfilesSA.Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioEmpleado")]
    public interface IServicioEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        PerfilesSA.Entidades.RespuestaServicio InsertarEmpleado(PerfilesSA.Entidades.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> InsertarEmpleadoAsync(PerfilesSA.Entidades.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        PerfilesSA.Entidades.RespuestaServicio ActualizarEmpleado(PerfilesSA.Entidades.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> ActualizarEmpleadoAsync(PerfilesSA.Entidades.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/CambiarEstadoEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/CambiarEstadoEmpleadoResponse")]
        PerfilesSA.Entidades.RespuestaServicio CambiarEstadoEmpleado(int idEmpleado, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/CambiarEstadoEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/CambiarEstadoEmpleadoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> CambiarEstadoEmpleadoAsync(int idEmpleado, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerEmpleadoPorId", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerEmpleadoPorIdResponse")]
        PerfilesSA.Entidades.Empleado ObtenerEmpleadoPorId(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerEmpleadoPorId", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerEmpleadoPorIdResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado> ObtenerEmpleadoPorIdAsync(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerTodosLosEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerTodosLosEmpleadosResponse")]
        PerfilesSA.Entidades.Empleado[] ObtenerTodosLosEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerTodosLosEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerTodosLosEmpleadosResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado[]> ObtenerTodosLosEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerReporteEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerReporteEmpleadosResponse")]
        PerfilesSA.Entidades.Empleado[] ObtenerReporteEmpleados(System.Nullable<int> idDepartamento, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ObtenerReporteEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ObtenerReporteEmpleadosResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado[]> ObtenerReporteEmpleadosAsync(System.Nullable<int> idDepartamento, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleadoChannel : PerfilesSA.Web.ServiceReference1.IServicioEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleadoClient : System.ServiceModel.ClientBase<PerfilesSA.Web.ServiceReference1.IServicioEmpleado>, PerfilesSA.Web.ServiceReference1.IServicioEmpleado {
        
        public ServicioEmpleadoClient() {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PerfilesSA.Entidades.RespuestaServicio InsertarEmpleado(PerfilesSA.Entidades.Empleado empleado) {
            return base.Channel.InsertarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> InsertarEmpleadoAsync(PerfilesSA.Entidades.Empleado empleado) {
            return base.Channel.InsertarEmpleadoAsync(empleado);
        }
        
        public PerfilesSA.Entidades.RespuestaServicio ActualizarEmpleado(PerfilesSA.Entidades.Empleado empleado) {
            return base.Channel.ActualizarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> ActualizarEmpleadoAsync(PerfilesSA.Entidades.Empleado empleado) {
            return base.Channel.ActualizarEmpleadoAsync(empleado);
        }
        
        public PerfilesSA.Entidades.RespuestaServicio CambiarEstadoEmpleado(int idEmpleado, bool activo) {
            return base.Channel.CambiarEstadoEmpleado(idEmpleado, activo);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> CambiarEstadoEmpleadoAsync(int idEmpleado, bool activo) {
            return base.Channel.CambiarEstadoEmpleadoAsync(idEmpleado, activo);
        }
        
        public PerfilesSA.Entidades.Empleado ObtenerEmpleadoPorId(int idEmpleado) {
            return base.Channel.ObtenerEmpleadoPorId(idEmpleado);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado> ObtenerEmpleadoPorIdAsync(int idEmpleado) {
            return base.Channel.ObtenerEmpleadoPorIdAsync(idEmpleado);
        }
        
        public PerfilesSA.Entidades.Empleado[] ObtenerTodosLosEmpleados() {
            return base.Channel.ObtenerTodosLosEmpleados();
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado[]> ObtenerTodosLosEmpleadosAsync() {
            return base.Channel.ObtenerTodosLosEmpleadosAsync();
        }
        
        public PerfilesSA.Entidades.Empleado[] ObtenerReporteEmpleados(System.Nullable<int> idDepartamento, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.ObtenerReporteEmpleados(idDepartamento, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Empleado[]> ObtenerReporteEmpleadosAsync(System.Nullable<int> idDepartamento, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.ObtenerReporteEmpleadosAsync(idDepartamento, fechaDesde, fechaHasta);
        }
    }
}
