//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfilesSA.Web.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServicioDepartamento")]
    public interface IServicioDepartamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/InsertarDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/InsertarDepartamentoResponse")]
        PerfilesSA.Entidades.RespuestaServicio InsertarDepartamento(PerfilesSA.Entidades.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/InsertarDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/InsertarDepartamentoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> InsertarDepartamentoAsync(PerfilesSA.Entidades.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ActualizarDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/ActualizarDepartamentoResponse")]
        PerfilesSA.Entidades.RespuestaServicio ActualizarDepartamento(PerfilesSA.Entidades.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ActualizarDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/ActualizarDepartamentoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> ActualizarDepartamentoAsync(PerfilesSA.Entidades.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/CambiarEstadoDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/CambiarEstadoDepartamentoResponse")]
        PerfilesSA.Entidades.RespuestaServicio CambiarEstadoDepartamento(int idDepartamento, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/CambiarEstadoDepartamento", ReplyAction="http://tempuri.org/IServicioDepartamento/CambiarEstadoDepartamentoResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> CambiarEstadoDepartamentoAsync(int idDepartamento, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentoPorId", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentoPorIdResponse")]
        PerfilesSA.Entidades.Departamento ObtenerDepartamentoPorId(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentoPorId", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentoPorIdResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento> ObtenerDepartamentoPorIdAsync(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerTodosLosDepartamentos", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerTodosLosDepartamentosResponse")]
        PerfilesSA.Entidades.Departamento[] ObtenerTodosLosDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerTodosLosDepartamentos", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerTodosLosDepartamentosResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento[]> ObtenerTodosLosDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentosActivos", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentosActivosResponse")]
        PerfilesSA.Entidades.Departamento[] ObtenerDepartamentosActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentosActivos", ReplyAction="http://tempuri.org/IServicioDepartamento/ObtenerDepartamentosActivosResponse")]
        System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento[]> ObtenerDepartamentosActivosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDepartamentoChannel : PerfilesSA.Web.ServiceReference2.IServicioDepartamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoClient : System.ServiceModel.ClientBase<PerfilesSA.Web.ServiceReference2.IServicioDepartamento>, PerfilesSA.Web.ServiceReference2.IServicioDepartamento {
        
        public ServicioDepartamentoClient() {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PerfilesSA.Entidades.RespuestaServicio InsertarDepartamento(PerfilesSA.Entidades.Departamento departamento) {
            return base.Channel.InsertarDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> InsertarDepartamentoAsync(PerfilesSA.Entidades.Departamento departamento) {
            return base.Channel.InsertarDepartamentoAsync(departamento);
        }
        
        public PerfilesSA.Entidades.RespuestaServicio ActualizarDepartamento(PerfilesSA.Entidades.Departamento departamento) {
            return base.Channel.ActualizarDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> ActualizarDepartamentoAsync(PerfilesSA.Entidades.Departamento departamento) {
            return base.Channel.ActualizarDepartamentoAsync(departamento);
        }
        
        public PerfilesSA.Entidades.RespuestaServicio CambiarEstadoDepartamento(int idDepartamento, bool activo) {
            return base.Channel.CambiarEstadoDepartamento(idDepartamento, activo);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.RespuestaServicio> CambiarEstadoDepartamentoAsync(int idDepartamento, bool activo) {
            return base.Channel.CambiarEstadoDepartamentoAsync(idDepartamento, activo);
        }
        
        public PerfilesSA.Entidades.Departamento ObtenerDepartamentoPorId(int idDepartamento) {
            return base.Channel.ObtenerDepartamentoPorId(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento> ObtenerDepartamentoPorIdAsync(int idDepartamento) {
            return base.Channel.ObtenerDepartamentoPorIdAsync(idDepartamento);
        }
        
        public PerfilesSA.Entidades.Departamento[] ObtenerTodosLosDepartamentos() {
            return base.Channel.ObtenerTodosLosDepartamentos();
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento[]> ObtenerTodosLosDepartamentosAsync() {
            return base.Channel.ObtenerTodosLosDepartamentosAsync();
        }
        
        public PerfilesSA.Entidades.Departamento[] ObtenerDepartamentosActivos() {
            return base.Channel.ObtenerDepartamentosActivos();
        }
        
        public System.Threading.Tasks.Task<PerfilesSA.Entidades.Departamento[]> ObtenerDepartamentosActivosAsync() {
            return base.Channel.ObtenerDepartamentosActivosAsync();
        }
    }
}
